// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelQuery() {
  return window['go']['main']['App']['CancelQuery']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function GetCellValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetCellValue'](arg1, arg2, arg3, arg4, arg5);
}

export function GetFilteredTableData(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetFilteredTableData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetTableData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetTableStructure(arg1, arg2) {
  return window['go']['main']['App']['GetTableStructure'](arg1, arg2);
}

export function InvalidateTableCache(arg1, arg2) {
  return window['go']['main']['App']['InvalidateTableCache'](arg1, arg2);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function ListObjects(arg1) {
  return window['go']['main']['App']['ListObjects'](arg1);
}

export function ListSchemas() {
  return window['go']['main']['App']['ListSchemas']();
}

export function SaveQueryResultEdits(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveQueryResultEdits'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
