// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CancelQuery():Promise<void>;

export function Connect(arg1:models.ConnectionConfig):Promise<models.ConnectionState>;

export function Disconnect():Promise<void>;

export function ExecuteQuery(arg1:string):Promise<models.QueryResult>;

export function GetCellValue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetFilteredTableData(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string,arg7:models.TableLookupFilter):Promise<models.TableDataPage>;

export function GetTableData(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<models.TableDataPage>;

export function GetTableStructure(arg1:string,arg2:string):Promise<Array<models.ColumnInfo>>;

export function InvalidateTableCache(arg1:string,arg2:string):Promise<void>;

export function IsConnected():Promise<boolean>;

export function ListDatabases():Promise<Array<string>>;

export function ListObjects(arg1:string):Promise<Array<models.DatabaseObject>>;

export function ListSchemas():Promise<Array<string>>;

export function SaveQueryResultEdits(arg1:string,arg2:string,arg3:Array<models.RowUpdate>):Promise<void>;

export function TestConnection(arg1:models.ConnectionConfig):Promise<void>;
